### ISSUE TITLE
Question: How well is the controller working in the dark ?

### ISSUE THREAD

**Issue by EloiStree** [EloiStree/CodeAndQuestsEveryDay#4]
In the total darkness. The Quest is deactivated. The controller are detected.
So you need at least some light (or infrared see #121 ) for the Quest to work.

**Comment by CycyTheMac** [comment]
In the total dark, it's not possible to the headset to track the controllers. 
I try with a led band that is behind my screens and it's working for the part of my room where the light of my screens and led band are effective. So when they are in my back, it's not working anymore...
In this conditions, the guardian is not recognized, so you have to reset it.
